targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          generate_for:
            - lib/**
            - packages/**
      auto_route_generator:auto_router_generator:
        options:
          generate_for:
            - lib/**
            - packages/**